apiVersion: skaffold/v4beta13
kind: Config

build:
  local:
    push: false

  artifacts:
    - image: cost-explorer-backend
      context: app/backend
      docker:
        dockerfile: Dockerfile
    - image: cost-explorer-frontend
      context: app/frontend
      docker:
        dockerfile: Dockerfile
  tagPolicy:
    sha256: {}
manifests:
  rawYaml:
    - k8s/*.yaml

portForward:
  - resourceType: service
    resourceName: cost-explorer-service-frontend
    namespace: frontend
    port: 8080
    localPort: 8080