apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.backendDeploymentName }}
  namespace: {{ .Values.backendNamespaceName }}
  labels:
    app: {{ .Values.backendImageName }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.backendImageName }}
  template:
    metadata:
      labels:
        app: {{ .Values.backendImageName }}
    spec:
      containers:
      - name: {{ .Values.backendImageName }}
        image: {{ .Values.backendImageName }}
        imagePullPolicy: IfNotPresent
        envFrom:
        - secretRef:
            name: {{ .Values.backendPostgresSecretName }}
        env:
        - name: POSTGRES_HOST
          value: {{ .Values.backendPostgresServiceName }}
        - name: POSTGRES_PORT
          value: "5432"
        resources:
          requests:
            memory: {{ .Values.requests.memory | quote }}
            cpu: {{ .Values.requests.cpu | quote }}
          limits:
            memory: {{ .Values.limits.memory | quote }}
            cpu: {{ .Values.limits.cpu | quote }}
        ports:
        - containerPort: 3000
      initContainers:
      - name: wait-for-postgres
        image: {{ .Values.backendPostgresImageName }}
        command:
          - sh
          - -c
          - until pg_isready -h {{ .Values.backendPostgresServiceName }} -p 5432; do echo waiting for postgres; sleep 2; done
        


