apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontendServiceName }}
  namespace: {{ .Values.frontendNamespaceName }}
  {{- if eq .Values.frontendServiceType "LoadBalancer" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  {{- end }}
spec:
  type: {{ .Values.frontendServiceType }}
  selector:
    app: {{ .Values.frontendImageName }}
  ports:
    - port: 8080
      targetPort: 80
      {{- if eq .Values.frontendServiceType "NodePort" }}
      nodePort: {{ .Values.frontendNodePort }}
      {{- end }}