apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backendPostgresSecretName }}
  namespace: {{ .Values.backendNamespaceName }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.backendPostgresUser | quote }}
  POSTGRES_PASSWORD: {{ .Values.backendPostgresPassword | quote }}
  POSTGRES_DB: {{ .Values.backendPostgresDb | quote }}
