{{- if .Values.postgresPersistentStorage }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.backendPvcName }}
  namespace: {{ .Values.backendNamespaceName }}
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- end }}