apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: dashboard-cluster-reader-role
rules:
- apiGroups: [""]
  resources: ["nodes", "pods", "services", "endpoints", "persistentvolumeclaims", "persistentvolumes"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-cluster-reader-binding
subjects:
- kind: ServiceAccount
  name: {{ .Values.backendServiceAccountName | default "default"}}
  namespace: {{ .Values.backendNamespaceName }}
roleRef:
  kind: ClusterRole
  name: dashboard-cluster-reader-role
  apiGroup: rbac.authorization.k8s.io
